# This is a basic workflow to help you get started with Actions

name: publish

# Controls when the workflow will run
on:
  push:
    branches:
      - "main"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: publish
        run: |
          echo "=======publish======"
          version_changed=$(git diff -- package.json  HEAD^ HEAD | grep "version" || true)
          [ -z "$version_changed" ] && exit 0

          npm install -g @vscode/vsce
          npm install
          #vsce package
          #file=$(realpath $(ls -t *.vsix | head -1))
          vsce publish -p ${{ secrets.VSCE_TOKEN }}
          

