# This is a basic workflow to help you get started with Actions

name: publish

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  pack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - uses: lannonbr/vsce-action@3.0.0
        with:
          args: "package"
      - uses: actions/upload-artifact@v2.3.1
        with: 
          path: |
            /github/workspace/*.vsix          
        
